import pandas as pd
import os

# Utility for heuristic validation of DataFrame schema constructs generated by the LLM pipeline.
OUTPUT_DIR = "../outputs"

def check_outputs():
    """Iterates serialized target files and emits dimensional shape properties and schema headers."""
    for f in os.listdir(OUTPUT_DIR):
        if f.endswith(".xlsx"):
            path = os.path.join(OUTPUT_DIR, f)
            print(f"--- Matrix: {f} ---")
            
            df = pd.read_excel(path)
            print("Schema Properties (Columns):", list(df.columns))
            print("Dimensionality (Shape):", df.shape)
            
            # Smoke test data row
            if not df.empty:
                print("Head vector [0]:", df.iloc[0].to_dict())
            print()

if __name__ == "__main__":
    check_outputs()
